<?php

namespace Clickedu\Machine\Tests\Unit\Console;

use PHPUnit\Framework\TestCase;

class MachineCommandTest extends TestCase
{
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testAssertTrue()
    {
        $this->assertTrue(true);
    }
}
